# Generated by Django 2.0.6 on 2018-06-28 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('gvector', models.FileField(upload_to='gvector/')),
                ('is_in_queue', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=0, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'gvectors',
            },
        ),
    ]
